#!/usr/bin/env bash
# Configures a new Ubuntu machine to install nginx

apt-get -y update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
