#!/usr/bin/env bash
# Configures a new Ubuntu machine

apt -y update
apt install -y nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www

echo 'Hello World!' |sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_hostname=$(hostname | sed 's/^[0-9]\+-//')

# configure redirect for a single page(/redirect_me) and add header to display hostname
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $new_hostname;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-enabled/default

# configure redirect for 404 error page
sed -i "s/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;\n\terror_page 404 \/404.html;\n\tlocation \/404.html{\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-enabled/default

sudo service nginx restart
