#!/usr/bin/env bash
# Fix nginx port 80 bug
apt-get -y update
apt install -y nginx
apt install -y ufw
ufw allow 'Nginx HTTP'
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
